services:

  django:
    build: 
      context: .
      dockerfile: docker/prod.dockerfile
    ports:
      - 8000:8000
    env_file:
      - .env

  db:
    image: postgres
    environment:
      POSTGRES_DB: "grupy"
      POSTGRES_USER: "grupy"
      POSTGRES_PASSWORD: "senha_super_segura"
    ports:
      - 5432:5432

  migrations:
    build: 
      context: .
      dockerfile: docker/prod.dockerfile
    depends_on:
      - django
      - db
    command: "python manage.py migrate"
    env_file:
      - .env

  web:
    build: ./docker/nginx
    ports:
      - 1337:80
    depends_on:
      - django
