services:

  web:
    build: 
      context: .
      dockerfile: docker/dev.dockerfile
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app

  db:
    image: postgres
    environment:
      POSTGRES_DB: "grupy"
      POSTGRES_USER: "grupy"
      POSTGRES_PASSWORD: "senha_super_segura"
    ports:
      - 5432:5432